obj-$(CONFIG_VFIO) += vfio.o
obj-$(CONFIG_VFIO_IOMMU_TYPE1) += vfio_iommu_type1.o
obj-$(CONFIG_VFIO_IOMMU_FSL_PAMU) += vfio_iommu_fsl_pamu.o
obj-$(CONFIG_VFIO_IOMMU_DUMMY) += vfio_iommu_dummy.o
obj-$(CONFIG_VFIO_PCI) += pci/
obj-$(CONFIG_VFIO_FSL_PCI_EP) += fsl_pci_ep/
